### PR TITLE
fix route.h file not found in ios11

### PR DESCRIPTION
**Pull request by BassamHabash**
xcode-select --install

### CODE REVIEW

**Comment by ZackMattor** [comment]
Hey @BassamHabash, was this to fix the simulator issue?

**Comment by cgraham-zmtp** [comment]
haha, yes, it is to fix the issue where route.h isn't found. I found his PR while trying to get the ios simulator to work with cordova tonight :smile:

**Comment by cgraham-zmtp** [comment]
I'll test it and see if it works

**Comment by cgraham-zmtp** [comment]
Closing this because it is superceded by https://github.com/violetatrium/cordova-plugin-get-router-ip-address/pull/2. Thanks @BassamHabash for your PR, we used it to make the next one.

**Pull request closed without merging**
